apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: default
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etcd-backup
            image: amazonlinux:2
            env:
            - name: AWS_ACCESS_KEY_ID
              value: "${AWS_ACCESS_KEY_ID}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "${AWS_SECRET_ACCESS_KEY}"
            volumeMounts:
            - name: backup-scripts
              mountPath: /scripts
            - name: k3s-data
              mountPath: /var/lib/rancher/k3s/server/db/snapshots
            command: ["/bin/bash", "-c", "/scripts/backup_etcd.sh"]
          volumes:
          - name: backup-scripts
            configMap:
              name: backup-scripts
          - name: k3s-data
            hostPath:
              path: /var/lib/rancher/k3s/server/db/snapshots
          restartPolicy: OnFailure
